site_name: Code Chronicle

nav:
  - ğŸ  Home: index.md
  - âš™ï¸ Setup: setup/readme.md
  - â˜ï¸ Azure:
      - AZ-204 Guide: az-204/az-204.md
  - ğŸ’» Programming:
      - Python Basics: python/python.md
  - âš™ï¸ DevOps:
      # - 1. Introduction: docker/dummy/docker-1-intro.md
      # - 2. Benefits of Docker: docker/dummy/docker-2-benefits.md
      # - 3. Docker vs VMs: docker/dummy/docker-3-vm-vs-containers.md
      # - 4. Docker Architecture: docker/dummy/docker-4-architecture.md
      - Docker Notes: docker/docker.md
      - Kubernetes Notes: k8s/k8s.md


theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: slate
      primary: cyan
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - navigation.footer
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
  
  
  