site_name: "ğŸš€ Code Chronicle"

nav:
  - ğŸ  Home: index.md

  - ğŸ›¢ï¸ Database:
      - ğŸ˜ PostgreSQL: database/postgreSQL.md
      - ğŸ’§ Liquibase: database/Liquidbase.md

  - ğŸ§ª Testing:
      - ğŸ§¬ JUnit: java/junit.md

  - â˜ï¸ Cloud:
      - ğŸ”· Azure:
          - ğŸ“˜ AZ-204 Guide: az-204/az-204.md

  - ğŸ’» Programming:
      - â˜• Java:
          - ğŸ§© Java Basics: java/JavaBasics.md
          - ğŸ§± Java OOP's: java/JavaOOps.md
          - ğŸ§  Advanced Java: java/AdvancedJava.md
          - ğŸ” Java8+: java/expertJava.md
      - ğŸ Python Basics: python/python.md

  - âš™ï¸ DevOps:
      - ğŸ³ Docker Notes: docker/docker.md
      - â˜¸ï¸ Kubernetes Notes: k8s/k8s.md

  - ğŸ§µ Queues:
      - ğŸ“¦ RMQ: queues/rmq.md
      - ğŸ“¨ Kafka: queues/kafka.md

  - ğŸ› ï¸ Setup: setup/readme.md

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: slate
      primary: cyan
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - navigation.footer
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
